# -*- coding: utf-8 -*-
"""Taller #1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tOgLj7PWw-eZwBxoG-WZUFWO_Uv37T00

**Taller Osmel Montalvo**
"""

Num_IdPers="1022428551"
print(Num_IdPers)
NombrePer="Osmel" " " "David"
print(NombrePer)
ApellPer="Montalvo" " " "Miranda"
print(ApellPer)
Direc="cl.128#51-68"
print(Direc)
Tlf="3113980496"
print(Tlf)
Edad ="28"
print(Edad)
EstCivil="Soltero"
print(EstCivil)
NumHijos="2"
print(NumHijos)
Estatura="1,78Cm"
print(Estatura)
Contratacion="22/Abril/2023"
print(Contratacion)
Sueld="1.800.000"
print(Sueld)
DiasLab="110 Dias"
print(DiasLab)

"""**Taller 2**"""

Edad = input("Digite la edad del empleado: ")
if Edad > "55":
  print("Cuenta con bono de pension ")
else:
  print("No cuenta con la edad para su bono de pension")
EstadoCivil = input("Digite el estado civil del empleado: ")
if EstadoCivil == "casado":
  print("Tiene derecho a paseo en diciembre")
else:
  print("No tiene derecho a paseo en diciembre")
Hijos = input("Tiene Hijos? ")
if Hijos or si:
  print("Tiene derecho a paseo en diciembre")
else:
  print("No tiene derecho a paseo en diciembre")
Sueldo = 1800000
if Sueldo < 2000000 and Sueldo >1500001:
   print(f"Su comision es = {Comision} y su salario total es = {Total}")
else:
   print("No tiene comision")
Comision = Sueldo * 0.05
Total = Sueldo + Comision
Dias = int(input("Digite los dias laborados"))
if Dias > 20:
  print("Tiene derecho a bono de alimentacion")
else:
  print("No tiene derecho a bono de alimentacion")